set_property PACKAGE_PIN AB7 [get_ports CPU_RESET]
set_property PACKAGE_PIN G8 [get_ports GTREFCLK_P]
set_property PACKAGE_PIN H2 [get_ports SFP_TX_P]
set_property PACKAGE_PIN AD12 [get_ports SYSCLK_P]
set_property PACKAGE_PIN AB8 [get_ports {LED[0]}]
set_property PACKAGE_PIN AA8 [get_ports {LED[1]}]
set_property PACKAGE_PIN AC9 [get_ports {LED[2]}]
set_property PACKAGE_PIN AB9 [get_ports {LED[3]}]
set_property PACKAGE_PIN AE26 [get_ports {LED[4]}]
set_property PACKAGE_PIN G19 [get_ports {LED[5]}]
set_property PACKAGE_PIN E18 [get_ports {LED[6]}]
set_property PACKAGE_PIN F16 [get_ports {LED[7]}]

create_clock -period 8.000 -name GTREFCLK_P -waveform {0.000 4.000} [get_ports GTREFCLK_P]
create_clock -period 5.000 -name SYSCLK_P -waveform {0.000 2.500} [get_ports SYSCLK_P]
set_property ASYNC_REG true [get_cells {gbe_i/gbe_i/frame_tx_i/FRAME_CONSTR/transferToRdClock/sync_q_reg[20]}]
set_property ASYNC_REG true [get_cells {gbe_i/gbe_i/frame_tx_i/FRAME_CONSTR/transferToRdClock/gen_others.gen_flipflops[2].sync_q_reg[36]}]
set_property ASYNC_REG true [get_cells {gbe_i/gbe_i/frame_tx_i/FRAME_CONSTR/transferToRdClock/gen_others.gen_flipflops[2].sync_q_reg[47]}]
set_property ASYNC_REG true [get_cells {gbe_i/gbe_i/frame_tx_i/FRAME_CONSTR/transferToRdClock/sync_q_reg[31]}]
set_property ASYNC_REG true [get_cells {gbe_i/gbe_i/frame_tx_i/FRAME_CONSTR/transferToRdClock/sync_q_reg[30]}]
set_property ASYNC_REG true [get_cells {gbe_i/gbe_i/frame_tx_i/FRAME_CONSTR/transferToRdClock/gen_others.gen_flipflops[2].sync_q_reg[46]}]
set_property ASYNC_REG true [get_cells {gbe_i/gbe_i/frame_tx_i/FRAME_CONSTR/transferToRdClock/gen_others.gen_flipflops[2].sync_q_reg[40]}]
set_property ASYNC_REG true [get_cells {gbe_i/gbe_i/frame_tx_i/FRAME_CONSTR/transferToRdClock/sync_q_reg[24]}]
set_property ASYNC_REG true [get_cells {gbe_i/gbe_i/frame_tx_i/FRAME_CONSTR/transferToRdClock/sync_q_reg[23]}]
set_property ASYNC_REG true [get_cells {gbe_i/gbe_i/frame_tx_i/FRAME_CONSTR/transferToRdClock/gen_others.gen_flipflops[2].sync_q_reg[39]}]
set_property ASYNC_REG true [get_cells {gbe_i/gbe_i/frame_tx_i/FRAME_CONSTR/transferToRdClock/sync_q_reg[22]}]
set_property ASYNC_REG true [get_cells {gbe_i/gbe_i/frame_tx_i/FRAME_CONSTR/transferToRdClock/gen_others.gen_flipflops[2].sync_q_reg[38]}]
set_property ASYNC_REG true [get_cells {gbe_i/gbe_i/frame_tx_i/FRAME_CONSTR/transferToRdClock/sync_q_reg[21]}]
set_property ASYNC_REG true [get_cells {gbe_i/gbe_i/frame_tx_i/FRAME_CONSTR/transferToRdClock/gen_others.gen_flipflops[2].sync_q_reg[37]}]
set_property ASYNC_REG true [get_cells {gbe_i/gbe_i/frame_tx_i/FRAME_CONSTR/transferToRdClock/sync_q_reg[17]}]
set_property ASYNC_REG true [get_cells {gbe_i/gbe_i/frame_tx_i/FRAME_CONSTR/transferToRdClock/gen_others.gen_flipflops[2].sync_q_reg[33]}]
set_property ASYNC_REG true [get_cells {gbe_i/gbe_i/frame_tx_i/FRAME_CONSTR/transferToRdClock/gen_others.gen_flipflops[2].sync_q_reg[44]}]
set_property ASYNC_REG true [get_cells {gbe_i/gbe_i/frame_tx_i/FRAME_CONSTR/transferToRdClock/sync_q_reg[28]}]
set_property ASYNC_REG true [get_cells {gbe_i/gbe_i/frame_tx_i/FRAME_CONSTR/transferToRdClock/gen_others.gen_flipflops[2].sync_q_reg[32]}]
set_property ASYNC_REG true [get_cells {gbe_i/gbe_i/frame_tx_i/FRAME_CONSTR/transferToRdClock/sync_q_reg[16]}]
set_property ASYNC_REG true [get_cells {gbe_i/gbe_i/frame_tx_i/FRAME_CONSTR/transferToRdClock/gen_others.gen_flipflops[2].sync_q_reg[43]}]
set_property ASYNC_REG true [get_cells {gbe_i/gbe_i/frame_tx_i/FRAME_CONSTR/transferToRdClock/sync_q_reg[27]}]
set_property ASYNC_REG true [get_cells {gbe_i/gbe_i/frame_tx_i/FRAME_CONSTR/transferToRdClock/sync_q_reg[26]}]
set_property ASYNC_REG true [get_cells {gbe_i/gbe_i/frame_tx_i/FRAME_CONSTR/transferToRdClock/gen_others.gen_flipflops[2].sync_q_reg[42]}]
set_property ASYNC_REG true [get_cells {gbe_i/gbe_i/frame_tx_i/FRAME_CONSTR/transferToRdClock/sync_q_reg[25]}]
set_property ASYNC_REG true [get_cells {gbe_i/gbe_i/frame_tx_i/FRAME_CONSTR/transferToRdClock/gen_others.gen_flipflops[2].sync_q_reg[41]}]
set_property ASYNC_REG true [get_cells {gbe_i/gbe_i/frame_tx_i/FRAME_CONSTR/transferToRdClock/gen_others.gen_flipflops[2].sync_q_reg[35]}]
set_property ASYNC_REG true [get_cells {gbe_i/gbe_i/frame_tx_i/FRAME_CONSTR/transferToRdClock/sync_q_reg[19]}]
set_property ASYNC_REG true [get_cells {gbe_i/gbe_i/frame_tx_i/FRAME_CONSTR/transferToRdClock/gen_others.gen_flipflops[2].sync_q_reg[34]}]
set_property ASYNC_REG true [get_cells {gbe_i/gbe_i/frame_tx_i/FRAME_CONSTR/transferToRdClock/sync_q_reg[18]}]
set_property ASYNC_REG true [get_cells {gbe_i/gbe_i/frame_tx_i/FRAME_CONSTR/transferToRdClock/gen_others.gen_flipflops[2].sync_q_reg[45]}]
set_property ASYNC_REG true [get_cells {gbe_i/gbe_i/frame_tx_i/FRAME_CONSTR/transferToRdClock/sync_q_reg[29]}]
set_clock_groups -asynchronous -group [get_clocks clkout1] -group [get_clocks GTREFCLK_P]
set_property ASYNC_REG true [get_cells gbe_i/gbe_i/frame_rx_i/FRAME_RECEIVER/FRAME_VALID_SYNC/sync_q_reg]
set_property ASYNC_REG true [get_cells gbe_i/gbe_i/frame_rx_i/FRAME_RECEIVER/FRAME_VALID_SYNC/sync_qq_reg]
set_clock_groups -asynchronous -group [get_clocks GTREFCLK_P] -group [get_clocks clkout1]


set_property IOSTANDARD LVCMOS25 [get_ports {LED[7]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LED[6]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LED[5]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LED[4]}]
set_property IOSTANDARD LVCMOS15 [get_ports {LED[0]}]
set_property IOSTANDARD LVCMOS15 [get_ports {LED[1]}]
set_property IOSTANDARD LVCMOS15 [get_ports {LED[2]}]
set_property IOSTANDARD LVCMOS15 [get_ports {LED[3]}]
set_property IOSTANDARD LVCMOS15 [get_ports CPU_RESET]
set_property IOSTANDARD DIFF_SSTL15 [get_ports SYSCLK_P]




set_property MARK_DEBUG false [get_nets {gbe_i/gbe_i/main_control/protocol_selector/PS_SRC_MAC_ADDRESS_IN[44]}]
set_property MARK_DEBUG false [get_nets {gbe_i/gbe_i/main_control/protocol_selector/PS_SRC_MAC_ADDRESS_IN[40]}]
set_property MARK_DEBUG false [get_nets {gbe_i/gbe_i/main_control/protocol_selector/PS_SRC_MAC_ADDRESS_IN[32]}]
set_property MARK_DEBUG false [get_nets {gbe_i/gbe_i/main_control/protocol_selector/PS_SRC_MAC_ADDRESS_IN[28]}]
set_property MARK_DEBUG false [get_nets {gbe_i/gbe_i/main_control/protocol_selector/PS_SRC_MAC_ADDRESS_IN[24]}]
set_property MARK_DEBUG false [get_nets {gbe_i/gbe_i/main_control/protocol_selector/PS_SRC_MAC_ADDRESS_IN[36]}]
set_property MARK_DEBUG false [get_nets {gbe_i/gbe_i/main_control/protocol_selector/PS_SRC_MAC_ADDRESS_IN[20]}]
set_property MARK_DEBUG false [get_nets {gbe_i/gbe_i/main_control/protocol_selector/PS_SRC_MAC_ADDRESS_IN[16]}]
set_property MARK_DEBUG false [get_nets {gbe_i/gbe_i/main_control/protocol_selector/PS_SRC_MAC_ADDRESS_IN[11]}]
set_property MARK_DEBUG false [get_nets {gbe_i/gbe_i/main_control/protocol_selector/PS_SRC_MAC_ADDRESS_IN[8]}]
set_property MARK_DEBUG false [get_nets {gbe_i/gbe_i/main_control/protocol_selector/PS_SRC_MAC_ADDRESS_IN[0]}]
set_property MARK_DEBUG false [get_nets {gbe_i/gbe_i/main_control/protocol_selector/PS_SRC_MAC_ADDRESS_IN[4]}]
set_property MARK_DEBUG false [get_nets {gbe_i/gbe_i/main_control/protocol_selector/PS_SRC_MAC_ADDRESS_IN[39]}]
set_property MARK_DEBUG false [get_nets {gbe_i/gbe_i/main_control/protocol_selector/PS_SRC_MAC_ADDRESS_IN[35]}]
set_property MARK_DEBUG false [get_nets {gbe_i/gbe_i/main_control/protocol_selector/PS_SRC_MAC_ADDRESS_IN[47]}]
set_property MARK_DEBUG false [get_nets {gbe_i/gbe_i/main_control/protocol_selector/PS_SRC_MAC_ADDRESS_IN[43]}]
set_property MARK_DEBUG false [get_nets {gbe_i/gbe_i/main_control/protocol_selector/PS_SRC_MAC_ADDRESS_IN[31]}]
set_property MARK_DEBUG false [get_nets {gbe_i/gbe_i/main_control/protocol_selector/PS_SRC_MAC_ADDRESS_IN[27]}]
set_property MARK_DEBUG false [get_nets {gbe_i/gbe_i/main_control/protocol_selector/PS_SRC_MAC_ADDRESS_IN[23]}]
set_property MARK_DEBUG false [get_nets {gbe_i/gbe_i/main_control/protocol_selector/PS_SRC_MAC_ADDRESS_IN[19]}]
set_property MARK_DEBUG false [get_nets {gbe_i/gbe_i/main_control/protocol_selector/PS_SRC_MAC_ADDRESS_IN[10]}]
set_property MARK_DEBUG false [get_nets {gbe_i/gbe_i/main_control/protocol_selector/PS_SRC_MAC_ADDRESS_IN[7]}]
set_property MARK_DEBUG false [get_nets {gbe_i/gbe_i/main_control/protocol_selector/PS_SRC_MAC_ADDRESS_IN[3]}]
set_property MARK_DEBUG false [get_nets {gbe_i/gbe_i/main_control/protocol_selector/PS_SRC_MAC_ADDRESS_IN[15]}]
set_property MARK_DEBUG false [get_nets {gbe_i/gbe_i/main_control/protocol_selector/PS_SRC_MAC_ADDRESS_IN[34]}]
set_property MARK_DEBUG false [get_nets {gbe_i/gbe_i/main_control/protocol_selector/PS_SRC_MAC_ADDRESS_IN[38]}]
set_property MARK_DEBUG false [get_nets {gbe_i/gbe_i/main_control/protocol_selector/PS_SRC_MAC_ADDRESS_IN[46]}]
set_property MARK_DEBUG false [get_nets {gbe_i/gbe_i/main_control/protocol_selector/PS_SRC_MAC_ADDRESS_IN[42]}]
set_property MARK_DEBUG false [get_nets {gbe_i/gbe_i/main_control/protocol_selector/PS_SRC_MAC_ADDRESS_IN[30]}]
set_property MARK_DEBUG false [get_nets {gbe_i/gbe_i/main_control/protocol_selector/PS_SRC_MAC_ADDRESS_IN[26]}]
set_property MARK_DEBUG false [get_nets {gbe_i/gbe_i/main_control/protocol_selector/PS_SRC_MAC_ADDRESS_IN[22]}]
set_property MARK_DEBUG false [get_nets {gbe_i/gbe_i/main_control/protocol_selector/PS_SRC_MAC_ADDRESS_IN[18]}]
set_property MARK_DEBUG false [get_nets {gbe_i/gbe_i/main_control/protocol_selector/PS_SRC_MAC_ADDRESS_IN[12]}]
set_property MARK_DEBUG false [get_nets {gbe_i/gbe_i/main_control/protocol_selector/PS_SRC_MAC_ADDRESS_IN[6]}]
set_property MARK_DEBUG false [get_nets {gbe_i/gbe_i/main_control/protocol_selector/PS_SRC_MAC_ADDRESS_IN[2]}]
set_property MARK_DEBUG false [get_nets {gbe_i/gbe_i/main_control/protocol_selector/PS_SRC_MAC_ADDRESS_IN[14]}]
set_property MARK_DEBUG false [get_nets {gbe_i/gbe_i/main_control/protocol_selector/PS_SRC_MAC_ADDRESS_IN[37]}]
set_property MARK_DEBUG false [get_nets {gbe_i/gbe_i/main_control/protocol_selector/PS_SRC_MAC_ADDRESS_IN[33]}]
set_property MARK_DEBUG false [get_nets {gbe_i/gbe_i/main_control/protocol_selector/PS_SRC_MAC_ADDRESS_IN[45]}]
set_property MARK_DEBUG false [get_nets {gbe_i/gbe_i/main_control/protocol_selector/PS_SRC_MAC_ADDRESS_IN[41]}]
set_property MARK_DEBUG false [get_nets {gbe_i/gbe_i/main_control/protocol_selector/PS_SRC_MAC_ADDRESS_IN[29]}]
set_property MARK_DEBUG false [get_nets {gbe_i/gbe_i/main_control/protocol_selector/PS_SRC_MAC_ADDRESS_IN[25]}]
set_property MARK_DEBUG false [get_nets {gbe_i/gbe_i/main_control/protocol_selector/PS_SRC_MAC_ADDRESS_IN[17]}]
set_property MARK_DEBUG false [get_nets {gbe_i/gbe_i/main_control/protocol_selector/PS_SRC_MAC_ADDRESS_IN[13]}]
set_property MARK_DEBUG false [get_nets {gbe_i/gbe_i/main_control/protocol_selector/PS_SRC_MAC_ADDRESS_IN[9]}]
set_property MARK_DEBUG false [get_nets {gbe_i/gbe_i/main_control/protocol_selector/PS_SRC_MAC_ADDRESS_IN[5]}]
set_property MARK_DEBUG false [get_nets {gbe_i/gbe_i/main_control/protocol_selector/PS_SRC_MAC_ADDRESS_IN[1]}]
set_property MARK_DEBUG false [get_nets {gbe_i/gbe_i/main_control/protocol_selector/PS_SRC_MAC_ADDRESS_IN[21]}]

set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/main_control/protocol_selector/PS_DATA_IN[0]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/main_control/protocol_selector/PS_DATA_IN[1]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/main_control/protocol_selector/PS_DATA_IN[2]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/main_control/protocol_selector/PS_DATA_IN[3]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/main_control/protocol_selector/PS_DATA_IN[4]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/main_control/protocol_selector/PS_DATA_IN[5]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/main_control/protocol_selector/PS_DATA_IN[6]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/main_control/protocol_selector/PS_DATA_IN[7]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/main_control/protocol_selector/PS_DATA_IN[8]}]
set_property MARK_DEBUG true [get_nets gbe_i/gbe_i/main_control/protocol_selector/PS_WR_EN_IN]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/main_control/protocol_selector/PS_PROTO_SELECT_IN[0]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/main_control/protocol_selector/PS_PROTO_SELECT_IN[1]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/main_control/protocol_selector/PS_PROTO_SELECT_IN[2]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/main_control/protocol_selector/PS_PROTO_SELECT_IN[3]}]
set_property MARK_DEBUG true [get_nets gbe_i/gbe_i/main_control/protocol_selector/full_receiver_gen.FullReceiver/PS_WR_EN_IN]
set_property MARK_DEBUG false [get_nets {gbe_i/gbe_i/main_control/RC_DATA_IN[8]}]
set_property MARK_DEBUG false [get_nets {gbe_i/gbe_i/main_control/RC_DATA_IN[6]}]
set_property MARK_DEBUG false [get_nets {gbe_i/gbe_i/main_control/RC_DATA_IN[5]}]
set_property MARK_DEBUG false [get_nets {gbe_i/gbe_i/main_control/RC_DATA_IN[1]}]
set_property MARK_DEBUG false [get_nets {gbe_i/gbe_i/main_control/RC_DATA_IN[0]}]
set_property MARK_DEBUG false [get_nets {gbe_i/gbe_i/main_control/RC_DATA_IN[7]}]
set_property MARK_DEBUG false [get_nets {gbe_i/gbe_i/main_control/RC_DATA_IN[4]}]
set_property MARK_DEBUG false [get_nets {gbe_i/gbe_i/main_control/RC_DATA_IN[3]}]
set_property MARK_DEBUG false [get_nets {gbe_i/gbe_i/main_control/RC_DATA_IN[2]}]

set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/main_control/protocol_selector/full_receiver_gen.FullReceiver/PS_DATA_IN[0]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/main_control/protocol_selector/full_receiver_gen.FullReceiver/PS_DATA_IN[1]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/main_control/protocol_selector/full_receiver_gen.FullReceiver/PS_DATA_IN[2]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/main_control/protocol_selector/full_receiver_gen.FullReceiver/PS_DATA_IN[3]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/main_control/protocol_selector/full_receiver_gen.FullReceiver/PS_DATA_IN[4]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/main_control/protocol_selector/full_receiver_gen.FullReceiver/PS_DATA_IN[5]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/main_control/protocol_selector/full_receiver_gen.FullReceiver/PS_DATA_IN[6]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/main_control/protocol_selector/full_receiver_gen.FullReceiver/PS_DATA_IN[7]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/main_control/protocol_selector/full_receiver_gen.FullReceiver/PS_DATA_IN[8]}]
set_property MARK_DEBUG true [get_nets gbe_i/gbe_i/main_control/protocol_selector/full_receiver_gen.FullReceiver/PS_ACTIVATE_IN]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/rc_q[0]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/rc_q[1]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/rc_q[2]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/rc_q[3]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/rc_q[4]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/rc_q[5]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/rc_q[6]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/rc_q[7]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/rc_q[8]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/rc_dest_ip[0]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/rc_dest_ip[10]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/rc_dest_ip[11]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/rc_dest_ip[12]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/rc_dest_ip[13]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/rc_dest_ip[14]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/rc_dest_ip[15]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/rc_dest_ip[16]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/rc_dest_ip[17]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/rc_dest_ip[18]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/rc_dest_ip[19]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/rc_dest_ip[1]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/rc_dest_ip[20]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/rc_dest_ip[21]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/rc_dest_ip[22]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/rc_dest_ip[23]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/rc_dest_ip[24]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/rc_dest_ip[25]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/rc_dest_ip[26]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/rc_dest_ip[27]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/rc_dest_ip[28]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/rc_dest_ip[29]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/rc_dest_ip[2]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/rc_dest_ip[30]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/rc_dest_ip[31]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/rc_dest_ip[3]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/rc_dest_ip[4]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/rc_dest_ip[5]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/rc_dest_ip[6]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/rc_dest_ip[7]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/rc_dest_ip[8]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/rc_dest_ip[9]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/rc_src_ip[0]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/rc_src_ip[10]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/rc_src_ip[11]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/rc_src_ip[12]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/rc_src_ip[13]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/rc_src_ip[14]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/rc_src_ip[15]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/rc_src_ip[16]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/rc_src_ip[17]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/rc_src_ip[18]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/rc_src_ip[19]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/rc_src_ip[1]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/rc_src_ip[20]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/rc_src_ip[21]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/rc_src_ip[22]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/rc_src_ip[23]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/rc_src_ip[24]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/rc_src_ip[25]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/rc_src_ip[26]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/rc_src_ip[27]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/rc_src_ip[28]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/rc_src_ip[29]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/rc_src_ip[2]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/rc_src_ip[30]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/rc_src_ip[31]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/rc_src_ip[3]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/rc_src_ip[4]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/rc_src_ip[5]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/rc_src_ip[6]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/rc_src_ip[7]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/rc_src_ip[8]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/rc_src_ip[9]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/rc_dest_udp[0]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/rc_dest_udp[10]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/rc_dest_udp[11]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/rc_dest_udp[12]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/rc_dest_udp[13]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/rc_dest_udp[14]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/rc_dest_udp[15]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/rc_dest_udp[1]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/rc_dest_udp[2]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/rc_dest_udp[3]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/rc_dest_udp[4]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/rc_dest_udp[5]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/rc_dest_udp[6]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/rc_dest_udp[7]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/rc_dest_udp[8]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/rc_dest_udp[9]}]

set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/main_control/protocol_selector/full_receiver_gen.FullReceiver/USR_DATA_OUT[0]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/main_control/protocol_selector/full_receiver_gen.FullReceiver/USR_DATA_OUT[1]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/main_control/protocol_selector/full_receiver_gen.FullReceiver/USR_DATA_OUT[2]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/main_control/protocol_selector/full_receiver_gen.FullReceiver/USR_DATA_OUT[3]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/main_control/protocol_selector/full_receiver_gen.FullReceiver/USR_DATA_OUT[4]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/main_control/protocol_selector/full_receiver_gen.FullReceiver/USR_DATA_OUT[5]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/main_control/protocol_selector/full_receiver_gen.FullReceiver/USR_DATA_OUT[6]}]
set_property MARK_DEBUG true [get_nets {gbe_i/gbe_i/main_control/protocol_selector/full_receiver_gen.FullReceiver/USR_DATA_OUT[7]}]
set_property MARK_DEBUG true [get_nets gbe_i/gbe_i/main_control/protocol_selector/full_receiver_gen.FullReceiver/USR_DATA_VALID_OUT]
set_property MARK_DEBUG true [get_nets gbe_i/gbe_i/main_control/protocol_selector/full_receiver_gen.FullReceiver/USR_EOP_OUT]
set_property MARK_DEBUG true [get_nets gbe_i/gbe_i/main_control/protocol_selector/full_receiver_gen.FullReceiver/USR_EOP_OUT0]
set_property MARK_DEBUG true [get_nets gbe_i/gbe_i/main_control/protocol_selector/full_receiver_gen.FullReceiver/USR_SOP_OUT]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 32768 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list clock_i/CLK_OUT2]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 8 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {gbe_i/gbe_i/main_control/protocol_selector/full_receiver_gen.FullReceiver/USR_DATA_OUT[0]} {gbe_i/gbe_i/main_control/protocol_selector/full_receiver_gen.FullReceiver/USR_DATA_OUT[1]} {gbe_i/gbe_i/main_control/protocol_selector/full_receiver_gen.FullReceiver/USR_DATA_OUT[2]} {gbe_i/gbe_i/main_control/protocol_selector/full_receiver_gen.FullReceiver/USR_DATA_OUT[3]} {gbe_i/gbe_i/main_control/protocol_selector/full_receiver_gen.FullReceiver/USR_DATA_OUT[4]} {gbe_i/gbe_i/main_control/protocol_selector/full_receiver_gen.FullReceiver/USR_DATA_OUT[5]} {gbe_i/gbe_i/main_control/protocol_selector/full_receiver_gen.FullReceiver/USR_DATA_OUT[6]} {gbe_i/gbe_i/main_control/protocol_selector/full_receiver_gen.FullReceiver/USR_DATA_OUT[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 1 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {gbe_i/gbe_i/main_control/protocol_selector/full_receiver_gen.FullReceiver/PS_DATA_IN[4]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 4 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {gbe_i/gbe_i/main_control/protocol_selector/PS_PROTO_SELECT_IN[0]} {gbe_i/gbe_i/main_control/protocol_selector/PS_PROTO_SELECT_IN[1]} {gbe_i/gbe_i/main_control/protocol_selector/PS_PROTO_SELECT_IN[2]} {gbe_i/gbe_i/main_control/protocol_selector/PS_PROTO_SELECT_IN[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 9 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {gbe_i/gbe_i/main_control/protocol_selector/PS_DATA_IN[0]} {gbe_i/gbe_i/main_control/protocol_selector/PS_DATA_IN[1]} {gbe_i/gbe_i/main_control/protocol_selector/PS_DATA_IN[2]} {gbe_i/gbe_i/main_control/protocol_selector/PS_DATA_IN[3]} {gbe_i/gbe_i/main_control/protocol_selector/PS_DATA_IN[4]} {gbe_i/gbe_i/main_control/protocol_selector/PS_DATA_IN[5]} {gbe_i/gbe_i/main_control/protocol_selector/PS_DATA_IN[6]} {gbe_i/gbe_i/main_control/protocol_selector/PS_DATA_IN[7]} {gbe_i/gbe_i/main_control/protocol_selector/PS_DATA_IN[8]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 32 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {gbe_i/gbe_i/rc_src_ip[0]} {gbe_i/gbe_i/rc_src_ip[1]} {gbe_i/gbe_i/rc_src_ip[2]} {gbe_i/gbe_i/rc_src_ip[3]} {gbe_i/gbe_i/rc_src_ip[4]} {gbe_i/gbe_i/rc_src_ip[5]} {gbe_i/gbe_i/rc_src_ip[6]} {gbe_i/gbe_i/rc_src_ip[7]} {gbe_i/gbe_i/rc_src_ip[8]} {gbe_i/gbe_i/rc_src_ip[9]} {gbe_i/gbe_i/rc_src_ip[10]} {gbe_i/gbe_i/rc_src_ip[11]} {gbe_i/gbe_i/rc_src_ip[12]} {gbe_i/gbe_i/rc_src_ip[13]} {gbe_i/gbe_i/rc_src_ip[14]} {gbe_i/gbe_i/rc_src_ip[15]} {gbe_i/gbe_i/rc_src_ip[16]} {gbe_i/gbe_i/rc_src_ip[17]} {gbe_i/gbe_i/rc_src_ip[18]} {gbe_i/gbe_i/rc_src_ip[19]} {gbe_i/gbe_i/rc_src_ip[20]} {gbe_i/gbe_i/rc_src_ip[21]} {gbe_i/gbe_i/rc_src_ip[22]} {gbe_i/gbe_i/rc_src_ip[23]} {gbe_i/gbe_i/rc_src_ip[24]} {gbe_i/gbe_i/rc_src_ip[25]} {gbe_i/gbe_i/rc_src_ip[26]} {gbe_i/gbe_i/rc_src_ip[27]} {gbe_i/gbe_i/rc_src_ip[28]} {gbe_i/gbe_i/rc_src_ip[29]} {gbe_i/gbe_i/rc_src_ip[30]} {gbe_i/gbe_i/rc_src_ip[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 9 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {gbe_i/gbe_i/rc_q[0]} {gbe_i/gbe_i/rc_q[1]} {gbe_i/gbe_i/rc_q[2]} {gbe_i/gbe_i/rc_q[3]} {gbe_i/gbe_i/rc_q[4]} {gbe_i/gbe_i/rc_q[5]} {gbe_i/gbe_i/rc_q[6]} {gbe_i/gbe_i/rc_q[7]} {gbe_i/gbe_i/rc_q[8]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 16 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list {gbe_i/gbe_i/rc_dest_udp[0]} {gbe_i/gbe_i/rc_dest_udp[1]} {gbe_i/gbe_i/rc_dest_udp[2]} {gbe_i/gbe_i/rc_dest_udp[3]} {gbe_i/gbe_i/rc_dest_udp[4]} {gbe_i/gbe_i/rc_dest_udp[5]} {gbe_i/gbe_i/rc_dest_udp[6]} {gbe_i/gbe_i/rc_dest_udp[7]} {gbe_i/gbe_i/rc_dest_udp[8]} {gbe_i/gbe_i/rc_dest_udp[9]} {gbe_i/gbe_i/rc_dest_udp[10]} {gbe_i/gbe_i/rc_dest_udp[11]} {gbe_i/gbe_i/rc_dest_udp[12]} {gbe_i/gbe_i/rc_dest_udp[13]} {gbe_i/gbe_i/rc_dest_udp[14]} {gbe_i/gbe_i/rc_dest_udp[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 32 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list {gbe_i/gbe_i/rc_dest_ip[0]} {gbe_i/gbe_i/rc_dest_ip[1]} {gbe_i/gbe_i/rc_dest_ip[2]} {gbe_i/gbe_i/rc_dest_ip[3]} {gbe_i/gbe_i/rc_dest_ip[4]} {gbe_i/gbe_i/rc_dest_ip[5]} {gbe_i/gbe_i/rc_dest_ip[6]} {gbe_i/gbe_i/rc_dest_ip[7]} {gbe_i/gbe_i/rc_dest_ip[8]} {gbe_i/gbe_i/rc_dest_ip[9]} {gbe_i/gbe_i/rc_dest_ip[10]} {gbe_i/gbe_i/rc_dest_ip[11]} {gbe_i/gbe_i/rc_dest_ip[12]} {gbe_i/gbe_i/rc_dest_ip[13]} {gbe_i/gbe_i/rc_dest_ip[14]} {gbe_i/gbe_i/rc_dest_ip[15]} {gbe_i/gbe_i/rc_dest_ip[16]} {gbe_i/gbe_i/rc_dest_ip[17]} {gbe_i/gbe_i/rc_dest_ip[18]} {gbe_i/gbe_i/rc_dest_ip[19]} {gbe_i/gbe_i/rc_dest_ip[20]} {gbe_i/gbe_i/rc_dest_ip[21]} {gbe_i/gbe_i/rc_dest_ip[22]} {gbe_i/gbe_i/rc_dest_ip[23]} {gbe_i/gbe_i/rc_dest_ip[24]} {gbe_i/gbe_i/rc_dest_ip[25]} {gbe_i/gbe_i/rc_dest_ip[26]} {gbe_i/gbe_i/rc_dest_ip[27]} {gbe_i/gbe_i/rc_dest_ip[28]} {gbe_i/gbe_i/rc_dest_ip[29]} {gbe_i/gbe_i/rc_dest_ip[30]} {gbe_i/gbe_i/rc_dest_ip[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list gbe_i/gbe_i/main_control/protocol_selector/full_receiver_gen.FullReceiver/PS_ACTIVATE_IN]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list gbe_i/gbe_i/main_control/protocol_selector/full_receiver_gen.FullReceiver/PS_WR_EN_IN]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 1 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list gbe_i/gbe_i/main_control/protocol_selector/PS_WR_EN_IN]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property port_width 1 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list gbe_i/gbe_i/main_control/protocol_selector/full_receiver_gen.FullReceiver/USR_DATA_VALID_OUT]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property port_width 1 [get_debug_ports u_ila_0/probe12]
connect_debug_port u_ila_0/probe12 [get_nets [list gbe_i/gbe_i/main_control/protocol_selector/full_receiver_gen.FullReceiver/USR_EOP_OUT]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property port_width 1 [get_debug_ports u_ila_0/probe13]
connect_debug_port u_ila_0/probe13 [get_nets [list gbe_i/gbe_i/main_control/protocol_selector/full_receiver_gen.FullReceiver/USR_EOP_OUT0]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property port_width 1 [get_debug_ports u_ila_0/probe14]
connect_debug_port u_ila_0/probe14 [get_nets [list gbe_i/gbe_i/main_control/protocol_selector/full_receiver_gen.FullReceiver/USR_SOP_OUT]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets independent_clock_bufg]
